// <auto-generated />
using System;
using Anderson_Nunez_AP1_P2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anderson_Nunez_AP1_P2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250715045604_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("int");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<decimal>("PesoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductosProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradaId");

                    b.HasIndex("ProductosProductoId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("EntradaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaDetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EntradaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradaDetalleId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradasDetalles");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCompuesto")
                        .HasColumnType("bit");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.Entradas", b =>
                {
                    b.HasOne("Anderson_Nunez_AP1_P2.Models.Productos", null)
                        .WithMany("EntradasProducidas")
                        .HasForeignKey("ProductosProductoId");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Anderson_Nunez_AP1_P2.Models.Entradas", "Entrada")
                        .WithMany("Detalles")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anderson_Nunez_AP1_P2.Models.Productos", "Producto")
                        .WithMany("EntradasDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.Entradas", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Anderson_Nunez_AP1_P2.Models.Productos", b =>
                {
                    b.Navigation("EntradasDetalles");

                    b.Navigation("EntradasProducidas");
                });
#pragma warning restore 612, 618
        }
    }
}
